export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const LOAD_URLS_SUCCESS = 'LOAD_URLS_SUCCESS';
export const CREATE_URL_SUCCESS = 'CREATE_URL_SUCCESS';
export const UPDATE_URL_SUCCESS = 'UPDATE_URL_SUCCESS';
export const UPDATE_URL_FAIL = 'UPDATE_URL_FAIL';
export const DELETE_URL_SUCCESS = 'DELETE_URL_SUCCESS';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_BAD_CREDS_USER = 'LOGIN_BAD_CREDS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';